import React, {useEffect}from 'react'
import { Swiper, SwiperSlide } from 'swiper/react'
import SwiperCore, {Scrollbar} from 'swiper'
import 'swiper/swiper-bundle.css';

SwiperCore.use([Scrollbar]);



const Gallery = () => {
    return(
        <>
            <Swiper id='main'
                slidesPerView={1}
                spaceBetween={30}
                scrollbar={true}
                freeMode={false}
                grabCursor={true}
                breakpoints={{
                    710:{
                        slidesPerView:2
                    },
                    970:{
                        slidesPerView:3
                    },
                    1050:{
                        slidesPerView:2
                    },
                    1180:{
                        slidesPerView:3
                    },
                    1415:{
                        slidesPerView:4
                        // freeMode: true
                    },
                    1675:{
                        slidesPerView:5
                    },
                    1950:{
                        slidesPerView:6
                    }
                }}
            >
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <SwiperSlide>
                    <div className="recomendation"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, error minus? Amet explicabo corporis commodi quasi dolor culpa dolorem ipsum architecto quas iure? Aliquam eos fugiat quidem, sequi aspernatur illo culpa nostrum ratione dignissimos voluptatibus perferendis aliquid officiis necessitatibus, maxime repellat alias facere ea excepturi debitis. Aperiam consequuntur provident ratione repudiandae. Reiciendis nesciunt eaque, fuga repellat dicta ut ducimus consequuntur repellendus ex asperiores rerum dolore voluptates illo. Laborum ipsam perferendis illo libero ullam dicta aliquam molestias neque quaerat adipisci ipsum, repellendus fugit laboriosam. Ipsa natus sapiente itaque, necessitatibus ab aut consequuntur quam in iure eum ducimus possimus laboriosam recusandae facilis adipisci provident ipsam minima reiciendis eius doloribus delectus, eos esse! Ipsa, quia voluptatem doloribus omnis sed qui eveniet? Id delectus veniam totam itaque incidunt, explicabo labore sint, laboriosam alias unde facere ea consectetur dolore quis earum obcaecati accusamus tempore repellendus odit vitae reprehenderit quo velit dicta. Placeat, doloribus unde cum, corrupti recusandae animi nostrum dolor quisquam accusantium quaerat tenetur. Numquam est nostrum aut veniam tenetur temporibus assumenda commodi praesentium cupiditate illo vitae tempora, iure, unde aperiam minus earum reiciendis similique incidunt reprehenderit quod perferendis ducimus! Totam sint nulla dolores accusantium, perspiciatis consequuntur deleniti veniam nemo voluptatibus quam in dolore cupiditate quidem incidunt dolorem facere similique. Quas in quibusdam rem id quae, consectetur fugiat veniam quis quasi, nesciunt perferendis pariatur est dolor repudiandae. Quo dolorem, ab explicabo vero veniam delectus? Recusandae voluptatum error fuga repellendus maxime quaerat officia obcaecati, maiores fugit vero quasi et eveniet accusantium accusamus quis quisquam commodi sed praesentium animi nobis molestiae eum ratione quam? Quos ipsam in velit iste exercitationem temporibus officia aperiam voluptate, atque veritatis corrupti et odio? Dicta suscipit nesciunt culpa blanditiis vero, quae modi praesentium ea eius magnam in ab veniam fuga explicabo provident vitae numquam, dolor harum? Dicta necessitatibus pariatur velit totam eos?</p></div>
                    <h6>Paweł</h6>
                </SwiperSlide>
                <br></br>
            </Swiper>
        </>
    )
}
export default Gallery;